; Test.Z80


; Amendment Record
; *****************
; Name          Date            Details of Amendment
; ----          ----            ---------------------
; Frank Martyn  2019-12-13     Initial coding


             .XLIST
;               ==============
;               External Files
;               ==============


;             include    MAC-SC.LIB
;             include    MyMac.LIB

;            ===================
;            External References
;            ===================

;             EXTRN      Prt00,PrtNL,PrtNLT,PrtAcc
             EXTRN      Prt00,Prt$,PrtNLT,PrtNL,PrtAcc
             EXTRN      Con00,Con$,ConNL

;               =============
;               Local Equates
;               =============
BDOS         EQU        0005H

ConOut       EQU        02H                  ; Console Out
LstOut       EQU        05H                  ; List Out

stackSize    EQU        20H                  ; depth of stack
FALSE        EQU        0                    ; False
TRUE         EQU        -1                   ; True

NULL         EQU        00                   ; 00H
LF           EQU        0AH                  ; Carriage Return
CR           EQU        0DH                  ; New Line
SPACE        EQU        20H                  ; SPACE
DOLLAR       EQU        '$'                  ; Dollar
lineSize     EQU        132                  ; max size of line
SYMBOL_SIZE  EQU        15                   ; Defined in ZMAC manual page 16 (20)
;**************************************************************************
                                             ;           ORG       TPA
             .LIST
START:
             LD         SP,stackTop

;            LD         DE,Msg1$
;            CALL       Con$
;            LD         DE,Msg2$
;            CALL       Con$
;
;            CALL       ConNL
;
;            LD         DE,Msg3$
;            CALL       Con$
;            LD         DE,Msg3$
;            CALL       Con$


             LD         DE,Msg1
             CALL       Con00
             LD         DE,Msg2
             CALL       Con00

             CALL       ConNL

             LD         DE,Msg3
             CALL       Con00
             LD         DE,Msg3
             CALL       Con00
             HALT



Msg1:        DB         'Null ',NULL
Msg2:        DB         'Terminated',NULL
Msg3:        DB         'Next Null Terminated Line.',CR,LF,NULL

Msg1$:       DB         'Dollar ',DOLLAR
Msg2$:       DB         'Terminated',DOLLAR
Msg3$:       DB         'Next DOLLAR Terminated Line.',CR,LF,DOLLAR

stackBottom:
             DS         stackSize            ; 16 level Stack
stackTop:                                    ; top of Stack


             END
